"use strict";

const fs = require("fs");
const path = require("path");

const CATEGORIES = [
	{ dir: "images/cats", varName: "CAT_IMAGES" },
	{ dir: "images/dogs", varName: "DOG_IMAGES" },
];

const IMAGE_EXTENSION_PATTERN = /\.(jpe?g|png|gif|webp)$/i;

function listImages(relDir) {
	const absDir = path.join(__dirname, "..", relDir);

	return fs
		.readdirSync(absDir)
		.filter((name) => IMAGE_EXTENSION_PATTERN.test(name))
		.sort()
		.map((name) => `${relDir}/${name}`.split("/").map(encodeURIComponent).join("/"));
}

function toArrayLiteral(varName, values) {
	const items = values.map((value) => `\t"${value}"`).join(",\n");
	return `const ${varName}: string[] = [\n${items}\n];`;
}

const blocks = CATEGORIES.map(({ dir, varName }) => toArrayLiteral(varName, listImages(dir)));

const output =
	"// Auto-generated by scripts/generate-images.js — do not edit by hand.\n" +
	'// Re-run "npm run generate:images" after adding/removing files under images/.\n\n' +
	blocks.join("\n\n") +
	"\n";

const outPath = path.join(__dirname, "..", "content_scripts", "images.ts");
fs.writeFileSync(outPath, output);
console.log(`Wrote ${outPath}`);
